const rares = [
  "Ancestral Recall",
  "Animate Wall",
  "Ankh of Mishra",
  "Armageddon",
  "Aspect of Wolf",
  "Badlands",
  "Bad Moon",
  "Balance",
  "Bayou",
  "Birds of Paradise",
  "Black Lotus",
  "Blaze of Glory",
  "Blessing",
  "Braingeyser",
  "Chaoslace",
  "Chaos Orb",
  "Clockwork Beast",
  "Cockatrice",
  "Copy Artifact",
  "Cyclopean Tomb",
  "Deathlace",
  "Demonic Hordes",
  "Dingus Egg",
  "Disrupting Scepter",
  "Drain Power",
  "Earthquake",
  "Elvish Archers",
  "Farmstead",
  "Fastbond",
  "Forcefield",
  "Force of Nature",
  "Fork",
  "Fungusaur",
  "Gaea's Liege",
  "Gauntlet of Might",
  "Goblin King",
  "Granite Gargoyle",
  "Helm of Chatzuk",
  "Howling Mine",
  "Illusionary Mask",
  "Island Sanctuary",
  "Jade Monolith",
  "Jayemdae Tome",
  "Kormus Bell",
  "Kudzu",
  "Lich",
  "Lifelace",
  "Living Artifact",
  "Living Lands",
  "Lord of Atlantis",
  "Lord of the Pit",
  "Magical Hack",
  "Mahamoti Djinn",
  "Manabarbs",
  "Mana Flare",
  "Mana Short",
  "Mana Vault",
  "Meekstone",
  "Mind Twist",
  "Mox Emerald",
  "Mox Jet",
  "Mox Pearl",
  "Mox Ruby",
  "Mox Sapphire",
  "Natural Selection",
  "Nether Shadow",
  "Nevinyrral's Disk",
  "Nightmare",
  "Northern Paladin",
  "Personal Incarnation",
  "Pirate Ship",
  "Plateau",
  "Power Surge",
  "Purelace",
  "Raging River",
  "Reverse Damage",
  "Righteousness",
  "Rock Hydra",
  "Roc of Kher Ridges",
  "Royal Assassin",
  "Savannah",
  "Savannah Lions",
  "Scrubland",
  "Sedge Troll",
  "Shivan Dragon",
  "Sleight of Mind",
  "Smoke",
  "Stasis",
  "Sunglasses of Urza",
  "Taiga",
  "The Hive",
  "Thoughtlace",
  "Timber Wolves",
  "Timetwister",
  "Time Vault",
  "Time Walk",
  "Tropical Island",
  "Tundra",
  "Two-Headed Giant of Foriys",
  "Underground Sea",
  "Verduran Enchantress",
  "Vesuvan Doppelganger",
  "Veteran Bodyguard",
  "Volcanic Eruption",
  "Volcanic Island",
  "Warp Artifact",
  "Web",
  "Wheel of Fortune",
  "Will-o'-the-Wisp",
  "Winter Orb",
  "Word of Command",
  "Wrath of God",
  "Zombie Master",
  "Tropical Island",
  "Tundra",
  "Volcanic Island",
  "Plateau",
  "Bayou",
  "Badlands",
  "Savannah",
  "Scrubland",
  "Underground Sea",
  "Taiga"
];

export default rares;
